/**
 * Minimal ABI fragments for the contract calls the frontend makes.
 * Full ABIs (generated from `forge build`) live in `frontend/src/config/full-abis/`
 * (regenerated by `pnpm abis`). The fragments below cover only what the UI hits at
 * runtime and keep the bundle small.
 */
export const erc20Abi = [
    {type: "function", name: "balanceOf", stateMutability: "view", inputs: [{name: "a", type: "address"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "allowance", stateMutability: "view", inputs: [{name: "o", type: "address"}, {name: "s", type: "address"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{name: "s", type: "address"}, {name: "a", type: "uint256"}], outputs: [{type: "bool"}]},
    {type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{name: "to", type: "address"}, {name: "a", type: "uint256"}], outputs: [{type: "bool"}]},
    {type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{type: "uint8"}]},
    {type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{type: "string"}]},
    {type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]}
] as const;

export const gameTokenAbi = [
    ...erc20Abi,
    {type: "function", name: "delegate", stateMutability: "nonpayable", inputs: [{name: "d", type: "address"}], outputs: []},
    {type: "function", name: "delegates", stateMutability: "view", inputs: [{name: "a", type: "address"}], outputs: [{type: "address"}]},
    {type: "function", name: "getVotes", stateMutability: "view", inputs: [{name: "a", type: "address"}], outputs: [{type: "uint256"}]}
] as const;

export const ammAbi = [
    {type: "function", name: "token0", stateMutability: "view", inputs: [], outputs: [{type: "address"}]},
    {type: "function", name: "token1", stateMutability: "view", inputs: [], outputs: [{type: "address"}]},
    {type: "function", name: "getReserves", stateMutability: "view", inputs: [], outputs: [{type: "uint112"}, {type: "uint112"}, {type: "uint32"}]},
    {type: "function", name: "getAmountOut", stateMutability: "pure", inputs: [{type: "uint256"}, {type: "uint256"}, {type: "uint256"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "swap", stateMutability: "nonpayable", inputs: [{name: "tokenIn", type: "address"}, {name: "amountIn", type: "uint256"}, {name: "amountOutMin", type: "uint256"}, {name: "to", type: "address"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "addLiquidity", stateMutability: "nonpayable", inputs: [{type: "uint256"}, {type: "uint256"}, {type: "uint256"}, {type: "uint256"}, {type: "address"}], outputs: [{type: "uint256"}, {type: "uint256"}, {type: "uint256"}]}
] as const;

export const vaultAbi = [
    ...erc20Abi,
    {type: "function", name: "asset", stateMutability: "view", inputs: [], outputs: [{type: "address"}]},
    {type: "function", name: "totalAssets", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]},
    {type: "function", name: "convertToAssets", stateMutability: "view", inputs: [{type: "uint256"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "deposit", stateMutability: "nonpayable", inputs: [{type: "uint256"}, {type: "address"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "redeem", stateMutability: "nonpayable", inputs: [{type: "uint256"}, {type: "address"}, {type: "address"}], outputs: [{type: "uint256"}]}
] as const;

export const governorAbi = [
    {type: "function", name: "state", stateMutability: "view", inputs: [{type: "uint256"}], outputs: [{type: "uint8"}]},
    {type: "function", name: "castVote", stateMutability: "nonpayable", inputs: [{type: "uint256"}, {type: "uint8"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "propose", stateMutability: "nonpayable", inputs: [{type: "address[]"}, {type: "uint256[]"}, {type: "bytes[]"}, {type: "string"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "queue", stateMutability: "nonpayable", inputs: [{type: "address[]"}, {type: "uint256[]"}, {type: "bytes[]"}, {type: "bytes32"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "execute", stateMutability: "payable", inputs: [{type: "address[]"}, {type: "uint256[]"}, {type: "bytes[]"}, {type: "bytes32"}], outputs: [{type: "uint256"}]}
] as const;

export const itemsAbi = [
    {type: "function", name: "balanceOf", stateMutability: "view", inputs: [{type: "address"}, {type: "uint256"}], outputs: [{type: "uint256"}]},
    {type: "function", name: "uri", stateMutability: "view", inputs: [{type: "uint256"}], outputs: [{type: "string"}]},
    {type: "function", name: "craft", stateMutability: "nonpayable", inputs: [{type: "uint256"}, {type: "uint256"}], outputs: []},
    {type: "function", name: "setApprovalForAll", stateMutability: "nonpayable", inputs: [{type: "address"}, {type: "bool"}], outputs: []}
] as const;

export const lootBoxAbi = [
    {type: "function", name: "openLootBox", stateMutability: "nonpayable", inputs: [], outputs: [{type: "uint256"}]},
    {type: "function", name: "rewardCount", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]}
] as const;
